config/routes.rb
Rails.application.routes.draw do
  resources :organization_data
  get '/index' => 'products#index'
  resources :products
  resources :categories
  resources :brands
  root 'products#index'

  put '/admins/:id/update', to: 'admins#update', as: 'update_admin'

  devise_for :admins, controllers: {
    passwords: 'passwords'
  }

  devise_scope :admin do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
 end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mercado
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
  - if admin_signed_in?
    .general-container
      .crud-nav
        .logo
          = image_tag(organization_logo, class: "logo-image")
        #navbarSupportedContent.navbar-collapse
          %ul.navbar-nav.mr-auto
            %li.nav-item
              %a.nav-link{:href => "/products", :class => current_page?("/products") ? "active" : "", style: current_page?("/products") ? "background-color: #{organization_color};" : ""}
                = image_tag("products.svg", class: "menu-icon")
                %span Produtos
            %li.nav-item
              %a.nav-link{:href => "/categories", :class => current_page?("/categories") ? "active" : "", style: current_page?("/categories") ? "background-color: #{organization_color};" : ""}
                = image_tag("categories.svg", class: "menu-icon")
                %span Categorias
            %li.nav-item
              %a.nav-link{:href => "/brands", :class => current_page?("/brands") ? "active" : "", style: current_page?("/brands") ? "background-color: #{organization_color};" : ""}
                = image_tag("brands.svg", class: "menu-icon")
                %span Marcas
      .general-content
        .page-header
          .search
          .admin
            = link_to image_tag("gear.svg", class: "gear-icon"), edit_registration_path(current_admin)
            = link_to image_tag("exit.svg", class: "exit-icon"), destroy_admin_session_path, method: :delete

        - if current_page?("/admins/edit")
          - flash.each do |type, msg|
            .alert.alert-info
              = msg
          = yield
        - else
          .container
            - flash.each do |type, msg|
              .alert.alert-info
                = msg
            = yield
  - else
    = yield
  = render 'ajax_modal_rails/frame'